### ISSUE TITLE
[Feature Request] Use `url-retrieve`  to fetch weather info

### ISSUE THREAD

**Issue by condy0919** [josegpt/display-wttr#17]
No requirement of curl, so it can run on windows out of box.

**Comment by josegpt** [comment]
Hello Condy0919,

If we would to drop the curl dependency, the capability to fetch multiple cities like this `https://wttr.in/{Nuremberg,Hamburg,Berlin}?format=3` will be lost since `url-retrieve` fetches info as a browser.

Unless we manage fetching multiple cities ourselves; consequently making multiple requests.

I will be taking a look into it.

**Comment by condy0919** [comment]
> Unless we manage fetching multiple cities ourselves; consequently making multiple requests.

```elisp
(dolist (city '("Nuremberg" "Hamburg" "Berlin"))
  (url-retrieve (format "https://wttr.in/%s?format=3" city)
                (lambda (_status)
                  (let ((buf (current-buffer))
                        (end (1+ url-http-end-of-headers)))
                    (with-temp-buffer
                      (insert-buffer-substring buf end)
                      (decode-coding-region (point-min) (point-max) 'utf-8)
                      (message "%s" (buffer-string)))))))
```

Since `url-retrieve` is async, it can be done in a loop. The same as curl does.

**Comment by josegpt** [comment]
I created a new pull request removing the curl dependency. Would you like to test it before a merge to `main`?

**Comment by condy0919** [comment]
It works, thanks.
